@FieldsAreNonnullByDefault
@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package com.hexagram2021.cme_suck_my_duck.containers;

import com.hexagram2021.cme_suck_my_duck.annotations.FieldsAreNonnullByDefault;
import com.hexagram2021.cme_suck_my_duck.annotations.MethodsReturnNonnullByDefault;
import com.hexagram2021.cme_suck_my_duck.annotations.ParametersAreNonnullByDefault;